# This template file is part of https://inetdoc.net project
#
# It defines the parameters used to customize Linux virtual machines with cloud-init
# on our type-2 hypervisors. The customization includes:
# - User creation with sudo privileges
# - SSH key deployment
# - Package installation
# - Network configuration with netplan
#
# Cloud-init key definitions:
# - force_seed: [true/false] force regeneration of seed.img file
# - users: list of users to create
#   - name: username for the new account
#   - sudo: sudo privileges for the account
#   - ssh_authorized_keys: list of SSH public keys to add
# - hostname: hostname to set on the virtual machine
# - packages: list of packages to install at first boot
# - netplan: network configuration using netplan format
#
# File: cloud-init-lab.yaml
# Author: Philippe Latu
# Source: https://gitlab.inetdoc.net/labs/startup-scripts
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

kvm:
  vms:
    - vm_name: vm1-cloud-init
      os: linux
      master_image: debian-testing-amd64.qcow2
      force_copy: false
      memory: 2048
      tapnum: 1
      devices:
        storage:
          - dev_name: vm1-nvme-disk1.qcow2
            type: disk
            size: 32G
            bus: nvme
      cloud_init:
        force_seed: false
        users:
          - name: admin
            sudo: ALL=(ALL) NOPASSWD:ALL
            ssh_authorized_keys:
              - ssh-ed25519 AAAA...
        hostname: vm1
        write_files:
          - path: /etc/systemd/system/vrf-ssh.service
            content: |
              [Unit]
              Description=OpenBSD Secure Shell server
              Documentation=man:sshd(8) man:sshd_config(5)
              After=network.target nss-user-lookup.target auditd.service
              ConditionPathExists=!/etc/ssh/sshd_not_to_be_run

              [Service]
              EnvironmentFile=-/etc/default/ssh
              ExecStartPre=/usr/sbin/ip vrf exec mgmt-vrf mkdir -p /run/sshd
              ExecStartPre=/usr/sbin/ip vrf exec mgmt-vrf chmod 0755 /run/sshd
              ExecStartPre=/usr/sbin/ip vrf exec mgmt-vrf /usr/sbin/sshd -t
              ExecStart=/usr/sbin/ip vrf exec mgmt-vrf /usr/sbin/sshd
              ExecReload=/usr/sbin/ip vrf exec mgmt-vrf /usr/sbin/sshd -t
              ExecReload=/bin/kill -HUP ${MAINPID}
              KillMode=process
              Restart=on-failure
              RestartPreventExitStatus=255
              Type=notify
              RuntimeDirectory=sshd
              RuntimeDirectoryMode=0755

              [Install]
              WantedBy=multi-user.target
              Alias=vrf-ssh.service
        runcmd:
          - systemctl daemon-reload
          - systemctl enable --now vrf-ssh.service
        packages:
          - openvswitch-switch
        netplan:
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp0s1:
                dhcp4: false
                dhcp6: false
            vlans:
              vlan68:
                id: 68
                link: enp0s1
                dhcp4: true
                dhcp6: false
                accept-ra: true
            vrfs:
              mgmt-vrf:
                table: 68
                interfaces:
                  - vlan68
